- id: '1618418559697'
  alias: Work From Home
  description: 'Sets light in bedroom to work from home mode. Only triggers on workdays
    at 8:30 AM. '
  trigger:
  - platform: time
    at: '8:30:00'
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - service: light.turn_on
    target:
      entity_id: light.bedroom
    data:
      color_temp: 300
      brightness_pct: 100
  mode: single

# - id: '435456543543546'
#   trigger:
#   - minutes: /1
#     platform: time
#     seconds: 0
#   condition:
#   - condition: template
#     value_template: '{{ (((as_timestamp(now()) | int) + 3*60) | timestamp_custom("%Y-%m-%d %H:%M:00")) == states.sensor.next_alarm.state }}'
#   action:
#   - data:
#       entity_id: scene.wakeup
#     service: scene.turn_on
