
##################################################################### 
#                         General Settings
#####################################################################
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes/

recorder:
  db_url: !secret recorder_url

# Text to speech
tts:
  - platform: google_translate


# Example configuration.yaml entry
http:
  cors_allowed_origins:
    - https://google.com
    - https://oauth.google.com
    - https://www.home-assistant.io
    - https://hassio.aaronslab.ca
    - https://oauth.aaronslab.ca
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.69.0/24

##################################################################### 
#           Lights (groups and switch-light conversions)
#####################################################################
light:
  
  # Create Groups of lights per room.
  - platform: group
    name: Bedroom
    entities:
      - light.bedroom_ceiling_1
      - light.bedroom_ceiling_2
      - light.bedroom_ceiling_3

  - platform: group
    name: Kitchen
    entities:
      - light.kitchen_light
      - light.kitchen_sink_light
      - light.main_door_light

  - platform: group
    name: Dinning Room
    entities:
      - light.dinning_room_light

  - platform: group
    name: Living Room
    entities:
      - light.bloomlight

  # Create Light Entities from switches. Makes them groupable.
  - platform: switch
    name: Main Door Light
    entity_id: switch.door_light

  - platform: switch
    name: Kitchen Light
    entity_id: switch.kitchen_main

  - platform: switch
    name: Dinning Room Light
    entity_id: switch.desk_light


##################################################################### 
#                 Sensors
#####################################################################
binary_sensor:
  # Work day sensor. Only is true Mon-Fri. Does not trigger on Holidays.
  - platform: workday
    country: CA
    province: BC
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun, holiday]

rest:
  - resource: "http://192.168.69.20:5000/api/v1/daily"
    verify_ssl: false
    scan_interval: 86400 # 24 hours
    sensor:
      - name: BCH_daily_usage
        value_template: "{{value_json.daily_usage}}"
        unit_of_measurement: "kWh"



sensor:
  - platform: integration
    source: sensor.BCH_daily_energy
    name: total_power
    round: 2


##################################################################### 
#                 Template Sensors
#####################################################################

template:
  - binary_sensor:
      - name: "Home Occupied"
        state: "{{ is_state('person.aaron', 'home') or is_state('person.gina', 'home')}}"


##################################################################### 
#                 Integrations
#####################################################################

# Example configuration.yaml entry
# nextcloud:
#   url: !secret nextcloud_url
#   username: !secret nextcloud_user
#   password: !secret nextcloud_pass

# Example configuration.yaml entry
neato:
  client_id: !secret neato_client_id
  client_secret: !secret neato_secret

##################################################################### 
#                 Misc File Includes
#####################################################################
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
