
##################################################################### 
#                         General Settings
#####################################################################
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


recorder:
  db_url: !secret recorder_url

# Text to speech
tts:
  - platform: google_translate

##################################################################### 
#           Lights (groups and switch-light conversions)
#####################################################################
light:
  
  # Create Groups of lights per room.
  - platform: group
    name: Bedroom
    entities:
      - light.bedroom_ceiling_1
      - light.bedroom_ceiling_2
      - light.bedroom_ceiling_3

  - platform: group
    name: Kitchen
    entities:
      - light.kitchen_light
      - light.kitchen_sink_light
      - light.main_door_light

  - platform: group
    name: Dinning Room
    entities:
      - light.dinning_room_light

  - platform: group
    name: Living Room
    entities:
      - light.bloomlight

  # Create Light Entities from switches. Makes them groupable.
  - platform: switch
    name: Main Door Light
    entity_id: switch.door_light

  - platform: switch
    name: Kitchen Light
    entity_id: switch.kitchen_main

  - platform: switch
    name: Dinning Room Light
    entity_id: switch.desk_light


##################################################################### 
#                 Sensors
#####################################################################
binary_sensor:
  # Work day sensor. Only is true Mon-Fri. Does not trigger on Holidays.
  - platform: workday
    country: CA
    province: BC
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun, holiday]

##################################################################### 
#                 Integrations
#####################################################################

# Example configuration.yaml entry
nextcloud:
  url: !secret nextcloud_url
  username: !secret nextcloud_user
  password: !secret nextcloud_pass

# Example configuration.yaml entry
neato:
  client_id: !secret neato_client_id
  client_secret: !secret neato_secret

##################################################################### 
#                 Misc File Includes
#####################################################################
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
